// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.

import { AlphaMode } from './generated/asset-schema/alpha-mode.js';
import { DetailLevel } from './generated/asset-schema/detail-level.js';

export { AlphaMode } from './generated/asset-schema/alpha-mode.js';
export { DetailLevel } from './generated/asset-schema/detail-level.js';
export { Vector2 as Vector2FB } from './generated/asset-schema/vector2.js';
export { Vector3 as Vector3FB } from './generated/asset-schema/vector3.js';
export { TextureTransformPacked } from './generated/asset-schema/texture-transform-packed.js';
export { TextureTransformPackedTight } from './generated/asset-schema/texture-transform-packed-tight.js';
export { TextureTransform as TextureTransformFB } from './generated/asset-schema/texture-transform.js';
export { GLTFMaterial as GLTFMaterialFB } from './generated/asset-schema/gltfmaterial.js';
export { JointInfluence as JointInfluenceFB } from './generated/asset-schema/joint-influence.js';
export { MeshBlock as MeshBlockFB } from './generated/asset-schema/mesh-block.js';
export { AssetMetadata } from './generated/asset-schema/asset-metadata.js';

export namespace AssetSchemaConstants {
    export const MAX_RIGGED_MESH_JOINTS: number = 256;
    export const JOINT_SENTINEL: number = 0xFF;

    export function getLodKey(lod: DetailLevel): string {
        switch (lod) {
            case DetailLevel.HIGHEST:
            case DetailLevel.HIGH:
                return "high_lod";
            case DetailLevel.MEDIUM:
                return "medium_lod";
            case DetailLevel.LOW:
                return "low_lod";
            case DetailLevel.LOWEST:
            default:
                return "lowest_lod";
        }
    }
}

export class TextureTransformAdapter {
    public scaleX: number = 1.0;
    public scaleY: number = 1.0;
    public rotation: number = 0.0;
    public offsetX: number = 0.0;
    public offsetY: number = 0.0;

    constructor(scaleX: number = 1.0, scaleY: number = 1.0, rotation: number = 0.0, offsetX: number = 0.0, offsetY: number = 0.0) {
        this.scaleX = scaleX;
        this.scaleY = scaleY;
        this.rotation = rotation;
        this.offsetX = offsetX;
        this.offsetY = offsetY;
    }

    public getPacked(): Float32Array {
        return new Float32Array([
            this.scaleX, this.scaleY, this.rotation, 0.0,
            this.offsetX, this.offsetY, 0.0, 0.0
        ]);
    }

    public getPackedTight(): Float32Array {
        return new Float32Array([
            this.scaleX, this.scaleY, this.rotation,
            this.offsetX, this.offsetY
        ]);
    }
}

export interface Vector2 {
    x: number;
    y: number;
}

export interface Vector3 {
    x: number;
    y: number;
    z: number;
}

export interface TextureTransform {
    readonly offset?: readonly [number, number];
    readonly scale?: readonly [number, number];
    readonly rotation?: number;
}

export interface JointInfluence {
    jointIndex?: number;
    jointName?: string;
    weight: number;
}

export interface GLTFMaterialAdapter {
    alphaMode: AlphaMode;
    alphaCutoff: number;
    doubleSided: boolean;
    transforms: TextureTransformAdapter[];
}

export interface MeshBlockAdapter {
    lod: DetailLevel;
    lodKey: string;
    positions: Vector3[];
    normals: Vector3[];
    texCoords: Vector2[];
    jointInfluences: JointInfluence[];
}
