<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Unified.LLSD</PackageId>
    <Version>1.0.0</Version>
    <Authors>Kaleaon</Authors>
    <Description>Zero-dependency idiomatic native C# LLSD (Linden Lab Structured Data) SDK library</Description>
  </PropertyGroup>
</Project>
