// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema;

public class AssetSchemaAdapter {
    public static final int MAX_RIGGED_MESH_JOINTS = 256;
    public static final int JOINT_SENTINEL = 0xFF;

    public enum AlphaMode {
        OPAQUE,
        MASK,
        BLEND
    }

    public enum DetailLevel {
        HIGHEST,
        HIGH,
        MEDIUM,
        LOW,
        LOWEST
    }

    public static String getLodKey(DetailLevel lod) {
        switch (lod) {
            case HIGHEST:
            case HIGH:
                return "high_lod";
            case MEDIUM:
                return "medium_lod";
            case LOW:
                return "low_lod";
            case LOWEST:
            default:
                return "lowest_lod";
        }
    }

    public static class TextureTransform {
        public float scaleX = 1.0f;
        public float scaleY = 1.0f;
        public float rotation = 0.0f;
        public float offsetX = 0.0f;
        public float offsetY = 0.0f;

        public float[] getPacked() {
            return new float[] { scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f };
        }

        public float[] getPackedTight() {
            return new float[] { scaleX, scaleY, rotation, offsetX, offsetY };
        }
    }

    public static class GLTFMaterial {
        public AlphaMode alphaMode = AlphaMode.OPAQUE;
        public float alphaCutoff = 0.5f;
        public boolean doubleSided = false;
        public java.util.List<TextureTransform> transforms = new java.util.ArrayList<>();

        public float[] getPacked(int index) {
            if (index >= 0 && index < transforms.size()) {
                return transforms.get(index).getPacked();
            }
            return new float[] { 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f };
        }

        public float[] getPackedTight(int index) {
            if (index >= 0 && index < transforms.size()) {
                return transforms.get(index).getPackedTight();
            }
            return new float[] { 1.0f, 1.0f, 0.0f, 0.0f, 0.0f };
        }
    }
}
