// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum AlphaMode {
    Opaque = 0,
    Mask = 1,
    Blend = 2,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum DetailLevel {
    Highest = 0,
    High = 1,
    Medium = 2,
    Low = 3,
    Lowest = 4,
}

pub const MAX_RIGGED_MESH_JOINTS: u32 = 256;
pub const JOINT_SENTINEL: u8 = 0xFF;

pub fn get_lod_key(lod: DetailLevel) -> &'static str {
    match lod {
        DetailLevel::Highest | DetailLevel::High => "high_lod",
        DetailLevel::Medium => "medium_lod",
        DetailLevel::Low => "low_lod",
        DetailLevel::Lowest => "lowest_lod",
    }
}

#[allow(non_snake_case)]
pub fn getLodKey(lod: DetailLevel) -> &'static str {
    get_lod_key(lod)
}

#[derive(Debug, Clone, PartialEq)]
pub struct TextureTransformAdapter {
    pub scale_x: f32,
    pub scale_y: f32,
    pub rotation: f32,
    pub offset_x: f32,
    pub offset_y: f32,
}

impl Default for TextureTransformAdapter {
    fn default() -> Self {
        Self {
            scale_x: 1.0,
            scale_y: 1.0,
            rotation: 0.0,
            offset_x: 0.0,
            offset_y: 0.0,
        }
    }
}

impl TextureTransformAdapter {
    pub fn new(scale_x: f32, scale_y: f32, rotation: f32, offset_x: f32, offset_y: f32) -> Self {
        Self {
            scale_x,
            scale_y,
            rotation,
            offset_x,
            offset_y,
        }
    }

    pub fn get_packed(&self) -> [f32; 8] {
        [self.scale_x, self.scale_y, self.rotation, 0.0, self.offset_x, self.offset_y, 0.0, 0.0]
    }

    pub fn get_packed_tight(&self) -> [f32; 5] {
        [self.scale_x, self.scale_y, self.rotation, self.offset_x, self.offset_y]
    }

    #[allow(non_snake_case)]
    pub fn getPacked(&self) -> [f32; 8] {
        self.get_packed()
    }

    #[allow(non_snake_case)]
    pub fn getPackedTight(&self) -> [f32; 5] {
        self.get_packed_tight()
    }
}
