// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema

enum class DetailLevel(val code: Int) {
    HIGHEST(0),
    HIGH(1),
    MEDIUM(2),
    LOW(3),
    LOWEST(4)
}

object AssetSchemaConstants {
    const val MAX_RIGGED_MESH_JOINTS: Int = 256
    const val JOINT_SENTINEL: Int = 0xFF

    fun getLodKey(lod: DetailLevel): String = when (lod) {
        DetailLevel.HIGHEST, DetailLevel.HIGH -> "high_lod"
        DetailLevel.MEDIUM -> "medium_lod"
        DetailLevel.LOW -> "low_lod"
        DetailLevel.LOWEST -> "lowest_lod"
    }
}

class TextureTransformAdapter(
    var scaleX: Float = 1.0f,
    var scaleY: Float = 1.0f,
    var rotation: Float = 0.0f,
    var offsetX: Float = 0.0f,
    var offsetY: Float = 0.0f
) {
    fun getPacked(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f
    )

    fun getPackedTight(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, offsetX, offsetY
    )
}

data class LodThresholdsAdapter(
    val highThreshold: Float = 200.0f,
    val mediumThreshold: Float = 80.0f,
    val lowThreshold: Float = 20.0f,
    val lowestThreshold: Float = 4.0f
)

data class SubmeshMaterialAdapter(
    val materialIndex: Int = 0,
    val indices: IntArray = intArrayOf(),
    val positions: FloatArray = floatArrayOf(),
    val normals: FloatArray = floatArrayOf(),
    val texCoords: FloatArray = floatArrayOf()
)
