// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
using System;
using System.Collections.Generic;

namespace Linkpoint.LLSD.Schema
{
    public enum AlphaMode : byte
    {
        Opaque = 0,
        Mask = 1,
        Blend = 2
    }

    public enum DetailLevel : byte
    {
        Highest = 0,
        High = 1,
        Medium = 2,
        Low = 3,
        Lowest = 4
    }

    public static class AssetSchemaConstants
    {
        public const int MAX_RIGGED_MESH_JOINTS = 256;
        public const byte JOINT_SENTINEL = 0xFF;

        public static string GetLodKey(DetailLevel lod)
        {
            switch (lod)
            {
                case DetailLevel.Highest:
                case DetailLevel.High:
                    return "high_lod";
                case DetailLevel.Medium:
                    return "medium_lod";
                case DetailLevel.Low:
                    return "low_lod";
                case DetailLevel.Lowest:
                default:
                    return "lowest_lod";
            }
        }
    }

    public class TextureTransformAdapter
    {
        public float ScaleX { get; set; } = 1.0f;
        public float ScaleY { get; set; } = 1.0f;
        public float Rotation { get; set; } = 0.0f;
        public float OffsetX { get; set; } = 0.0f;
        public float OffsetY { get; set; } = 0.0f;

        public float[] getPacked()
        {
            return new float[] { ScaleX, ScaleY, Rotation, 0.0f, OffsetX, OffsetY, 0.0f, 0.0f };
        }

        public float[] GetPacked() => getPacked();

        public float[] getPackedTight()
        {
            return new float[] { ScaleX, ScaleY, Rotation, OffsetX, OffsetY };
        }

        public float[] GetPackedTight() => getPackedTight();
    }

    public class GLTFMaterialAdapter
    {
        public AlphaMode AlphaMode { get; set; } = AlphaMode.Opaque;
        public float AlphaCutoff { get; set; } = 0.5f;
        public bool DoubleSided { get; set; } = false;
        public List<TextureTransformAdapter> Transforms { get; set; } = new List<TextureTransformAdapter>();

        public float[] getPacked(int index = 0)
        {
            if (index >= 0 && index < Transforms.Count)
                return Transforms[index].getPacked();
            return new float[] { 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f };
        }

        public float[] GetPacked(int index = 0) => getPacked(index);

        public float[] getPackedTight(int index = 0)
        {
            if (index >= 0 && index < Transforms.Count)
                return Transforms[index].getPackedTight();
            return new float[] { 1.0f, 1.0f, 0.0f, 0.0f, 0.0f };
        }

        public float[] GetPackedTight(int index = 0) => getPackedTight(index);
    }
}
