// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
import Foundation

public enum AlphaMode: UInt8 {
    case opaque = 0
    case mask = 1
    case blend = 2
}

public enum DetailLevel: UInt8 {
    case highest = 0
    case high = 1
    case medium = 2
    case low = 3
    case lowest = 4
}

public struct AssetSchemaConstants {
    public static let MAX_RIGGED_MESH_JOINTS: UInt32 = 256
    public static let JOINT_SENTINEL: UInt8 = 0xFF

    public static func getLodKey(_ lod: DetailLevel) -> String {
        switch lod {
        case .highest, .high:
            return "high_lod"
        case .medium:
            return "medium_lod"
        case .low:
            return "low_lod"
        case .lowest:
            return "lowest_lod"
        }
    }

    public static func getLodKey(lod: DetailLevel) -> String {
        return getLodKey(lod)
    }
}

public let MAX_RIGGED_MESH_JOINTS: UInt32 = 256
public let JOINT_SENTINEL: UInt8 = 0xFF

public func getLodKey(_ lod: DetailLevel) -> String {
    return AssetSchemaConstants.getLodKey(lod)
}

public func getLodKey(lod: DetailLevel) -> String {
    return AssetSchemaConstants.getLodKey(lod)
}

public func get_lod_key(_ lod: DetailLevel) -> String {
    return AssetSchemaConstants.getLodKey(lod)
}

public struct TextureTransformAdapter {
    public var scaleX: Float
    public var scaleY: Float
    public var rotation: Float
    public var offsetX: Float
    public var offsetY: Float

    public init(scaleX: Float = 1.0, scaleY: Float = 1.0, rotation: Float = 0.0, offsetX: Float = 0.0, offsetY: Float = 0.0) {
        self.scaleX = scaleX
        self.scaleY = scaleY
        self.rotation = rotation
        self.offsetX = offsetX
        self.offsetY = offsetY
    }

    public func getPacked() -> [Float] {
        return [scaleX, scaleY, rotation, 0.0, offsetX, offsetY, 0.0, 0.0]
    }

    public func getPackedTight() -> [Float] {
        return [scaleX, scaleY, rotation, offsetX, offsetY]
    }

    public func get_packed() -> [Float] {
        return getPacked()
    }

    public func get_packed_tight() -> [Float] {
        return getPackedTight()
    }
}
