// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema

enum class AlphaMode(val code: Int) {
    OPAQUE(0),
    MASK(1),
    BLEND(2)
}

enum class DetailLevel(val code: Int) {
    HIGHEST(0),
    HIGH(1),
    MEDIUM(2),
    LOW(3),
    LOWEST(4)
}

object AssetSchemaConstants {
    const val MAX_RIGGED_MESH_JOINTS: Int = 256
    const val JOINT_SENTINEL: Int = 0xFF

    fun getLodKey(lod: DetailLevel): String = when (lod) {
        DetailLevel.HIGHEST, DetailLevel.HIGH -> "high_lod"
        DetailLevel.MEDIUM -> "medium_lod"
        DetailLevel.LOW -> "low_lod"
        DetailLevel.LOWEST -> "lowest_lod"
    }
}

class TextureTransformAdapter(
    var scaleX: Float = 1.0f,
    var scaleY: Float = 1.0f,
    var rotation: Float = 0.0f,
    var offsetX: Float = 0.0f,
    var offsetY: Float = 0.0f
) {
    fun getPacked(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f
    )

    fun getPackedTight(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, offsetX, offsetY
    )
}

class GLTFMaterial(
    var alphaMode: AlphaMode = AlphaMode.OPAQUE,
    var alphaCutoff: Float = 0.5f,
    var doubleSided: Boolean = false,
    val transforms: MutableList<TextureTransformAdapter> = MutableList(5) { TextureTransformAdapter() }
) {
    fun getPacked(textureInfo: Int = 0): FloatArray =
        if (textureInfo in transforms.indices) transforms[textureInfo].getPacked()
        else floatArrayOf(1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f)

    fun getPackedTight(textureInfo: Int = 0): FloatArray =
        if (textureInfo in transforms.indices) transforms[textureInfo].getPackedTight()
        else floatArrayOf(1.0f, 1.0f, 0.0f, 0.0f, 0.0f)
}
