// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
#ifndef UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H
#define UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H

#include <cstdint>
#include <array>
#include <string>

namespace UnifiedLLSD {

enum class DetailLevel : uint8_t {
    Highest = 0,
    High = 1,
    Medium = 2,
    Low = 3,
    Lowest = 4
};

constexpr uint32_t MAX_RIGGED_MESH_JOINTS = 256;
constexpr uint8_t JOINT_SENTINEL = 0xFF;

inline const char* GetLodKey(DetailLevel lod) {
    switch (lod) {
        case DetailLevel::Highest:
        case DetailLevel::High:
            return "high_lod";
        case DetailLevel::Medium:
            return "medium_lod";
        case DetailLevel::Low:
            return "low_lod";
        case DetailLevel::Lowest:
        default:
            return "lowest_lod";
    }
}

struct TextureTransformAdapter {
    float scaleX = 1.0f;
    float scaleY = 1.0f;
    float rotation = 0.0f;
    float offsetX = 0.0f;
    float offsetY = 0.0f;

    std::array<float, 8> GetPacked() const {
        return { scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f };
    }

    std::array<float, 5> GetPackedTight() const {
        return { scaleX, scaleY, rotation, offsetX, offsetY };
    }
};

} // namespace UnifiedLLSD

#endif // UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H
