#!/usr/bin/env python3
"""
Automated cross-language code generator for Unified-LLSD asset schemas.
Generates native binding adapters and binary serializers for C++, Kotlin, C#,
Java, TypeScript, Rust, Swift, and Dart.
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))


def generate_cpp():
    cpp_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
#ifndef UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H
#define UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H

#include <cstdint>
#include <array>
#include <string>

namespace UnifiedLLSD {

enum class DetailLevel : uint8_t {
    Highest = 0,
    High = 1,
    Medium = 2,
    Low = 3,
    Lowest = 4
};

constexpr uint32_t MAX_RIGGED_MESH_JOINTS = 256;
constexpr uint8_t JOINT_SENTINEL = 0xFF;

inline const char* GetLodKey(DetailLevel lod) {
    switch (lod) {
        case DetailLevel::Highest:
        case DetailLevel::High:
            return "high_lod";
        case DetailLevel::Medium:
            return "medium_lod";
        case DetailLevel::Low:
            return "low_lod";
        case DetailLevel::Lowest:
        default:
            return "lowest_lod";
    }
}

struct TextureTransformAdapter {
    float scaleX = 1.0f;
    float scaleY = 1.0f;
    float rotation = 0.0f;
    float offsetX = 0.0f;
    float offsetY = 0.0f;

    std::array<float, 8> GetPacked() const {
        return { scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f };
    }

    std::array<float, 5> GetPackedTight() const {
        return { scaleX, scaleY, rotation, offsetX, offsetY };
    }
};

} // namespace UnifiedLLSD

#endif // UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "cpp")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "AssetSchemaAdapter.h"), "w") as f:
        f.write(cpp_code)


def generate_kotlin():
    kt_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema

enum class DetailLevel(val code: Int) {
    HIGHEST(0),
    HIGH(1),
    MEDIUM(2),
    LOW(3),
    LOWEST(4)
}

object AssetSchemaConstants {
    const val MAX_RIGGED_MESH_JOINTS: Int = 256
    const val JOINT_SENTINEL: Int = 0xFF

    fun getLodKey(lod: DetailLevel): String = when (lod) {
        DetailLevel.HIGHEST, DetailLevel.HIGH -> "high_lod"
        DetailLevel.MEDIUM -> "medium_lod"
        DetailLevel.LOW -> "low_lod"
        DetailLevel.LOWEST -> "lowest_lod"
    }
}

class TextureTransformAdapter(
    var scaleX: Float = 1.0f,
    var scaleY: Float = 1.0f,
    var rotation: Float = 0.0f,
    var offsetX: Float = 0.0f,
    var offsetY: Float = 0.0f
) {
    fun getPacked(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f
    )

    fun getPackedTight(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, offsetX, offsetY
    )
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "kotlin")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "AssetSchemaAdapter.kt"), "w") as f:
        f.write(kt_code)


def generate_csharp():
    cs_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
using System;

namespace Linkpoint.LLSD.Schema
{
    public enum DetailLevel : byte
    {
        Highest = 0,
        High = 1,
        Medium = 2,
        Low = 3,
        Lowest = 4
    }

    public static class AssetSchemaConstants
    {
        public const int MAX_RIGGED_MESH_JOINTS = 256;
        public const byte JOINT_SENTINEL = 0xFF;

        public static string GetLodKey(DetailLevel lod)
        {
            switch (lod)
            {
                case DetailLevel.Highest:
                case DetailLevel.High:
                    return "high_lod";
                case DetailLevel.Medium:
                    return "medium_lod";
                case DetailLevel.Low:
                    return "low_lod";
                case DetailLevel.Lowest:
                default:
                    return "lowest_lod";
            }
        }
    }

    public class TextureTransformAdapter
    {
        public float ScaleX { get; set; } = 1.0f;
        public float ScaleY { get; set; } = 1.0f;
        public float Rotation { get; set; } = 0.0f;
        public float OffsetX { get; set; } = 0.0f;
        public float OffsetY { get; set; } = 0.0f;

        public float[] GetPacked()
        {
            return new float[] { ScaleX, ScaleY, Rotation, 0.0f, OffsetX, OffsetY, 0.0f, 0.0f };
        }

        public float[] GetPackedTight()
        {
            return new float[] { ScaleX, ScaleY, Rotation, OffsetX, OffsetY };
        }
    }
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "csharp")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "AssetSchemaAdapter.cs"), "w") as f:
        f.write(cs_code)
    sdk_dir = os.path.join(REPO_ROOT, "csharp", "Linkpoint.LLSD", "Schema")
    os.makedirs(sdk_dir, exist_ok=True)
    with open(os.path.join(sdk_dir, "AssetSchemaAdapter.cs"), "w") as f:
        f.write(cs_code)


def generate_java():
    java_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema;

public class AssetSchemaAdapter {
    public static final int MAX_RIGGED_MESH_JOINTS = 256;
    public static final int JOINT_SENTINEL = 0xFF;

    public enum DetailLevel {
        HIGHEST,
        HIGH,
        MEDIUM,
        LOW,
        LOWEST
    }

    public static String getLodKey(DetailLevel lod) {
        switch (lod) {
            case HIGHEST:
            case HIGH:
                return "high_lod";
            case MEDIUM:
                return "medium_lod";
            case LOW:
                return "low_lod";
            case LOWEST:
            default:
                return "lowest_lod";
        }
    }

    public static class TextureTransform {
        public float scaleX = 1.0f;
        public float scaleY = 1.0f;
        public float rotation = 0.0f;
        public float offsetX = 0.0f;
        public float offsetY = 0.0f;

        public float[] getPacked() {
            return new float[] { scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f };
        }

        public float[] getPackedTight() {
            return new float[] { scaleX, scaleY, rotation, offsetX, offsetY };
        }
    }
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "java")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "AssetSchemaAdapter.java"), "w") as f:
        f.write(java_code)


def generate_typescript():
    ts_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.

export enum AlphaMode {
    OPAQUE = 0,
    MASK = 1,
    BLEND = 2
}

export enum DetailLevel {
    HIGHEST = 0,
    HIGH = 1,
    MEDIUM = 2,
    LOW = 3,
    LOWEST = 4
}

export namespace AssetSchemaConstants {
    export const MAX_RIGGED_MESH_JOINTS: number = 256;
    export const JOINT_SENTINEL: number = 0xFF;

    export function getLodKey(lod: DetailLevel): string {
        switch (lod) {
            case DetailLevel.HIGHEST:
            case DetailLevel.HIGH:
                return "high_lod";
            case DetailLevel.MEDIUM:
                return "medium_lod";
            case DetailLevel.LOW:
                return "low_lod";
            case DetailLevel.LOWEST:
            default:
                return "lowest_lod";
        }
    }
}

export class TextureTransformAdapter {
    public scaleX: number = 1.0;
    public scaleY: number = 1.0;
    public rotation: number = 0.0;
    public offsetX: number = 0.0;
    public offsetY: number = 0.0;

    constructor(scaleX: number = 1.0, scaleY: number = 1.0, rotation: number = 0.0, offsetX: number = 0.0, offsetY: number = 0.0) {
        this.scaleX = scaleX;
        this.scaleY = scaleY;
        this.rotation = rotation;
        this.offsetX = offsetX;
        this.offsetY = offsetY;
    }

    public getPacked(): Float32Array {
        return new Float32Array([
            this.scaleX, this.scaleY, this.rotation, 0.0,
            this.offsetX, this.offsetY, 0.0, 0.0
        ]);
    }

    public getPackedTight(): Float32Array {
        return new Float32Array([
            this.scaleX, this.scaleY, this.rotation,
            this.offsetX, this.offsetY
        ]);
    }
}

export interface Vector2 {
    x: number;
    y: number;
}

export interface Vector3 {
    x: number;
    y: number;
    z: number;
}

export interface JointInfluence {
    jointIndex: number;
    weight: number;
}

export interface GLTFMaterialAdapter {
    alphaMode: AlphaMode;
    alphaCutoff: number;
    doubleSided: boolean;
    transforms: TextureTransformAdapter[];
}

export interface MeshBlockAdapter {
    lod: DetailLevel;
    lodKey: string;
    positions: Vector3[];
    normals: Vector3[];
    texCoords: Vector2[];
    jointInfluences: JointInfluence[];
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "typescript")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "AssetSchemaAdapter.ts"), "w") as f:
        f.write(ts_code)


def generate_rust():
    rust_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum AlphaMode {
    Opaque = 0,
    Mask = 1,
    Blend = 2,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum DetailLevel {
    Highest = 0,
    High = 1,
    Medium = 2,
    Low = 3,
    Lowest = 4,
}

pub const MAX_RIGGED_MESH_JOINTS: u32 = 256;
pub const JOINT_SENTINEL: u8 = 0xFF;

pub fn get_lod_key(lod: DetailLevel) -> &'static str {
    match lod {
        DetailLevel::Highest | DetailLevel::High => "high_lod",
        DetailLevel::Medium => "medium_lod",
        DetailLevel::Low => "low_lod",
        DetailLevel::Lowest => "lowest_lod",
    }
}

#[allow(non_snake_case)]
pub fn getLodKey(lod: DetailLevel) -> &'static str {
    get_lod_key(lod)
}

#[derive(Debug, Clone, PartialEq)]
pub struct TextureTransformAdapter {
    pub scale_x: f32,
    pub scale_y: f32,
    pub rotation: f32,
    pub offset_x: f32,
    pub offset_y: f32,
}

impl Default for TextureTransformAdapter {
    fn default() -> Self {
        Self {
            scale_x: 1.0,
            scale_y: 1.0,
            rotation: 0.0,
            offset_x: 0.0,
            offset_y: 0.0,
        }
    }
}

impl TextureTransformAdapter {
    pub fn new(scale_x: f32, scale_y: f32, rotation: f32, offset_x: f32, offset_y: f32) -> Self {
        Self {
            scale_x,
            scale_y,
            rotation,
            offset_x,
            offset_y,
        }
    }

    pub fn get_packed(&self) -> [f32; 8] {
        [self.scale_x, self.scale_y, self.rotation, 0.0, self.offset_x, self.offset_y, 0.0, 0.0]
    }

    pub fn get_packed_tight(&self) -> [f32; 5] {
        [self.scale_x, self.scale_y, self.rotation, self.offset_x, self.offset_y]
    }

    #[allow(non_snake_case)]
    pub fn getPacked(&self) -> [f32; 8] {
        self.get_packed()
    }

    #[allow(non_snake_case)]
    pub fn getPackedTight(&self) -> [f32; 5] {
        self.get_packed_tight()
    }
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "rust")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "asset_schema_adapter.rs"), "w") as f:
        f.write(rust_code)
    sdk_dir = os.path.join(REPO_ROOT, "rust", "src")
    os.makedirs(sdk_dir, exist_ok=True)
    with open(os.path.join(sdk_dir, "asset_schema_adapter.rs"), "w") as f:
        f.write(rust_code)


def generate_swift():
    swift_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
import Foundation

public enum AlphaMode: UInt8 {
    case opaque = 0
    case mask = 1
    case blend = 2
}

public enum DetailLevel: UInt8 {
    case highest = 0
    case high = 1
    case medium = 2
    case low = 3
    case lowest = 4
}

public struct AssetSchemaConstants {
    public static let MAX_RIGGED_MESH_JOINTS: UInt32 = 256
    public static let JOINT_SENTINEL: UInt8 = 0xFF

    public static func getLodKey(_ lod: DetailLevel) -> String {
        switch lod {
        case .highest, .high:
            return "high_lod"
        case .medium:
            return "medium_lod"
        case .low:
            return "low_lod"
        case .lowest:
            return "lowest_lod"
        }
    }

    public static func getLodKey(lod: DetailLevel) -> String {
        return getLodKey(lod)
    }
}

public let MAX_RIGGED_MESH_JOINTS: UInt32 = 256
public let JOINT_SENTINEL: UInt8 = 0xFF

public func getLodKey(_ lod: DetailLevel) -> String {
    return AssetSchemaConstants.getLodKey(lod)
}

public func getLodKey(lod: DetailLevel) -> String {
    return AssetSchemaConstants.getLodKey(lod)
}

public func get_lod_key(_ lod: DetailLevel) -> String {
    return AssetSchemaConstants.getLodKey(lod)
}

public struct TextureTransformAdapter {
    public var scaleX: Float
    public var scaleY: Float
    public var rotation: Float
    public var offsetX: Float
    public var offsetY: Float

    public init(scaleX: Float = 1.0, scaleY: Float = 1.0, rotation: Float = 0.0, offsetX: Float = 0.0, offsetY: Float = 0.0) {
        self.scaleX = scaleX
        self.scaleY = scaleY
        self.rotation = rotation
        self.offsetX = offsetX
        self.offsetY = offsetY
    }

    public func getPacked() -> [Float] {
        return [scaleX, scaleY, rotation, 0.0, offsetX, offsetY, 0.0, 0.0]
    }

    public func getPackedTight() -> [Float] {
        return [scaleX, scaleY, rotation, offsetX, offsetY]
    }

    public func get_packed() -> [Float] {
        return getPacked()
    }

    public func get_packed_tight() -> [Float] {
        return getPackedTight()
    }
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "swift")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "AssetSchemaAdapter.swift"), "w") as f:
        f.write(swift_code)
    sdk_dir = os.path.join(REPO_ROOT, "swift", "Sources", "UnifiedLLSD")
    os.makedirs(sdk_dir, exist_ok=True)
    with open(os.path.join(sdk_dir, "AssetSchemaAdapter.swift"), "w") as f:
        f.write(swift_code)


def generate_dart():
    dart_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.

enum AlphaMode {
  opaque,
  mask,
  blend,
}

enum DetailLevel {
  highest,
  high,
  medium,
  low,
  lowest,
}

const int MAX_RIGGED_MESH_JOINTS = 256;
const int JOINT_SENTINEL = 0xFF;

class AssetSchemaConstants {
  static const int maxRiggedMeshJoints = 256;
  static const int jointSentinel = 0xFF;

  static String getLodKey(DetailLevel lod) {
    return get_lod_key(lod);
  }
}

String getLodKey(DetailLevel lod) {
  switch (lod) {
    case DetailLevel.highest:
    case DetailLevel.high:
      return 'high_lod';
    case DetailLevel.medium:
      return 'medium_lod';
    case DetailLevel.low:
      return 'low_lod';
    case DetailLevel.lowest:
      return 'lowest_lod';
  }
}

String get_lod_key(DetailLevel lod) => getLodKey(lod);

class TextureTransformAdapter {
  double scaleX;
  double scaleY;
  double rotation;
  double offsetX;
  double offsetY;

  TextureTransformAdapter({
    this.scaleX = 1.0,
    this.scaleY = 1.0,
    this.rotation = 0.0,
    this.offsetX = 0.0,
    this.offsetY = 0.0,
  });

  List<double> getPacked() {
    return [scaleX, scaleY, rotation, 0.0, offsetX, offsetY, 0.0, 0.0];
  }

  List<double> getPackedTight() {
    return [scaleX, scaleY, rotation, offsetX, offsetY];
  }

  List<double> get_packed() => getPacked();
  List<double> get_packed_tight() => getPackedTight();
}
"""
    bindings_dir = os.path.join(REPO_ROOT, "bindings", "dart")
    os.makedirs(bindings_dir, exist_ok=True)
    with open(os.path.join(bindings_dir, "asset_schema_adapter.dart"), "w") as f:
        f.write(dart_code)
    sdk_dir = os.path.join(REPO_ROOT, "dart", "lib")
    os.makedirs(sdk_dir, exist_ok=True)
    with open(os.path.join(sdk_dir, "asset_schema_adapter.dart"), "w") as f:
        f.write(dart_code)


def main():
    print("Generating C++ bindings...")
    generate_cpp()
    print("Generating Kotlin bindings...")
    generate_kotlin()
    print("Generating C# bindings...")
    generate_csharp()
    print("Generating Java bindings...")
    generate_java()
    print("Generating TypeScript bindings...")
    generate_typescript()
    print("Generating Rust bindings...")
    generate_rust()
    print("Generating Swift bindings...")
    generate_swift()
    print("Generating Dart bindings...")
    generate_dart()
    print("All language bindings generated successfully!")


if __name__ == "__main__":
    main()
