#!/usr/bin/env python3
"""
Automated cross-language code generator for Unified-LLSD asset schemas.
Generates native binding adapters and binary serializers for C++, Kotlin, C#, and Java.
"""

import os
import sys

def generate_cpp():
    cpp_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
#ifndef UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H
#define UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H

#include <cstdint>
#include <array>
#include <string>

namespace UnifiedLLSD {

enum class DetailLevel : uint8_t {
    Highest = 0,
    High = 1,
    Medium = 2,
    Low = 3,
    Lowest = 4
};

constexpr uint32_t MAX_RIGGED_MESH_JOINTS = 256;
constexpr uint8_t JOINT_SENTINEL = 0xFF;

inline const char* GetLodKey(DetailLevel lod) {
    switch (lod) {
        case DetailLevel::Highest:
        case DetailLevel::High:
            return "high_lod";
        case DetailLevel::Medium:
            return "medium_lod";
        case DetailLevel::Low:
            return "low_lod";
        case DetailLevel::Lowest:
        default:
            return "lowest_lod";
    }
}

struct TextureTransformAdapter {
    float scaleX = 1.0f;
    float scaleY = 1.0f;
    float rotation = 0.0f;
    float offsetX = 0.0f;
    float offsetY = 0.0f;

    std::array<float, 8> GetPacked() const {
        return { scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f };
    }

    std::array<float, 5> GetPackedTight() const {
        return { scaleX, scaleY, rotation, offsetX, offsetY };
    }
};

} // namespace UnifiedLLSD

#endif // UNIFIED_LLSD_ASSET_SCHEMA_ADAPTER_H
"""
    os.makedirs("/app/Unified-LLSD/bindings/cpp", exist_ok=True)
    with open("/app/Unified-LLSD/bindings/cpp/AssetSchemaAdapter.h", "w") as f:
        f.write(cpp_code)

def generate_kotlin():
    kt_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema

enum class DetailLevel(val code: Int) {
    HIGHEST(0),
    HIGH(1),
    MEDIUM(2),
    LOW(3),
    LOWEST(4)
}

object AssetSchemaConstants {
    const val MAX_RIGGED_MESH_JOINTS: Int = 256
    const val JOINT_SENTINEL: Int = 0xFF

    fun getLodKey(lod: DetailLevel): String = when (lod) {
        DetailLevel.HIGHEST, DetailLevel.HIGH -> "high_lod"
        DetailLevel.MEDIUM -> "medium_lod"
        DetailLevel.LOW -> "low_lod"
        DetailLevel.LOWEST -> "lowest_lod"
    }
}

class TextureTransformAdapter(
    var scaleX: Float = 1.0f,
    var scaleY: Float = 1.0f,
    var rotation: Float = 0.0f,
    var offsetX: Float = 0.0f,
    var offsetY: Float = 0.0f
) {
    fun getPacked(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f
    )

    fun getPackedTight(): FloatArray = floatArrayOf(
        scaleX, scaleY, rotation, offsetX, offsetY
    )
}
"""
    os.makedirs("/app/Unified-LLSD/bindings/kotlin", exist_ok=True)
    with open("/app/Unified-LLSD/bindings/kotlin/AssetSchemaAdapter.kt", "w") as f:
        f.write(kt_code)

def generate_csharp():
    cs_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
using System;

namespace UnifiedLLSD.Schema
{
    public enum DetailLevel : byte
    {
        Highest = 0,
        High = 1,
        Medium = 2,
        Low = 3,
        Lowest = 4
    }

    public static class AssetSchemaConstants
    {
        public const int MAX_RIGGED_MESH_JOINTS = 256;
        public const byte JOINT_SENTINEL = 0xFF;

        public static string GetLodKey(DetailLevel lod)
        {
            switch (lod)
            {
                case DetailLevel.Highest:
                case DetailLevel.High:
                    return "high_lod";
                case DetailLevel.Medium:
                    return "medium_lod";
                case DetailLevel.Low:
                    return "low_lod";
                case DetailLevel.Lowest:
                default:
                    return "lowest_lod";
            }
        }
    }

    public class TextureTransformAdapter
    {
        public float ScaleX { get; set; } = 1.0f;
        public float ScaleY { get; set; } = 1.0f;
        public float Rotation { get; set; } = 0.0f;
        public float OffsetX { get; set; } = 0.0f;
        public float OffsetY { get; set; } = 0.0f;

        public float[] GetPacked()
        {
            return new float[] { ScaleX, ScaleY, Rotation, 0.0f, OffsetX, OffsetY, 0.0f, 0.0f };
        }

        public float[] GetPackedTight()
        {
            return new float[] { ScaleX, ScaleY, Rotation, OffsetX, OffsetY };
        }
    }
}
"""
    os.makedirs("/app/Unified-LLSD/bindings/csharp", exist_ok=True)
    with open("/app/Unified-LLSD/bindings/csharp/AssetSchemaAdapter.cs", "w") as f:
        f.write(cs_code)

def generate_java():
    java_code = """// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.
package com.unifiedllsd.schema;

public class AssetSchemaAdapter {
    public static final int MAX_RIGGED_MESH_JOINTS = 256;
    public static final int JOINT_SENTINEL = 0xFF;

    public enum DetailLevel {
        HIGHEST,
        HIGH,
        MEDIUM,
        LOW,
        LOWEST
    }

    public static String getLodKey(DetailLevel lod) {
        switch (lod) {
            case HIGHEST:
            case HIGH:
                return "high_lod";
            case MEDIUM:
                return "medium_lod";
            case LOW:
                return "low_lod";
            case LOWEST:
            default:
                return "lowest_lod";
        }
    }

    public static class TextureTransform {
        public float scaleX = 1.0f;
        public float scaleY = 1.0f;
        public float rotation = 0.0f;
        public float offsetX = 0.0f;
        public float offsetY = 0.0f;

        public float[] getPacked() {
            return new float[] { scaleX, scaleY, rotation, 0.0f, offsetX, offsetY, 0.0f, 0.0f };
        }

        public float[] getPackedTight() {
            return new float[] { scaleX, scaleY, rotation, offsetX, offsetY };
        }
    }
}
"""
    os.makedirs("/app/Unified-LLSD/bindings/java", exist_ok=True)
    with open("/app/Unified-LLSD/bindings/java/AssetSchemaAdapter.java", "w") as f:
        f.write(java_code)

def main():
    print("Generating C++ bindings...")
    generate_cpp()
    print("Generating Kotlin bindings...")
    generate_kotlin()
    print("Generating C# bindings...")
    generate_csharp()
    print("Generating Java bindings...")
    generate_java()
    print("All language bindings generated successfully!")

if __name__ == "__main__":
    main()
