// Generated by Unified-LLSD scripts/generate_bindings.py. DO NOT EDIT DIRECTLY.

enum AlphaMode {
  opaque,
  mask,
  blend,
}

enum DetailLevel {
  highest,
  high,
  medium,
  low,
  lowest,
}

const int MAX_RIGGED_MESH_JOINTS = 256;
const int JOINT_SENTINEL = 0xFF;

class AssetSchemaConstants {
  static const int maxRiggedMeshJoints = 256;
  static const int jointSentinel = 0xFF;

  static String getLodKey(DetailLevel lod) {
    return get_lod_key(lod);
  }
}

String getLodKey(DetailLevel lod) {
  switch (lod) {
    case DetailLevel.highest:
    case DetailLevel.high:
      return 'high_lod';
    case DetailLevel.medium:
      return 'medium_lod';
    case DetailLevel.low:
      return 'low_lod';
    case DetailLevel.lowest:
      return 'lowest_lod';
  }
}

String get_lod_key(DetailLevel lod) => getLodKey(lod);

class TextureTransformAdapter {
  double scaleX;
  double scaleY;
  double rotation;
  double offsetX;
  double offsetY;

  TextureTransformAdapter({
    this.scaleX = 1.0,
    this.scaleY = 1.0,
    this.rotation = 0.0,
    this.offsetX = 0.0,
    this.offsetY = 0.0,
  });

  List<double> getPacked() {
    return [scaleX, scaleY, rotation, 0.0, offsetX, offsetY, 0.0, 0.0];
  }

  List<double> getPackedTight() {
    return [scaleX, scaleY, rotation, offsetX, offsetY];
  }

  List<double> get_packed() => getPacked();
  List<double> get_packed_tight() => getPackedTight();
}
